[providers]
  docker = true

[api]
  insecure = true

[entryPoints]
  [entryPoints.web]
    address = ":80"

[docker]

# Enable watch docker changes
#
# Optional
#
watch = true

[web]
# Web administration port
#
# Required
#
address = ":8080"


[consulCatalog]

# Docker server endpoint. Can be a tcp or a unix socket endpoint.
#
# Required
#
endpoint = "consul:8500"

# Default domain used.
# Can be overridden by setting the "traefik.domain" label on a container.
#
# Required
#
prefix = "traefik"

watch = true
exposedbydefault = false